# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20034_prefetch import InlineResponse20034Prefetch  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20034Prefetch(unittest.TestCase):
    """InlineResponse20034Prefetch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20034Prefetch
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20034_prefetch.InlineResponse20034Prefetch()  # noqa: E501
        if include_optional :
            return InlineResponse20034Prefetch(
                product_type = {
                    'key' : openapi_client.models.product_type.ProductType(
                        id = 56, 
                        name = '0', 
                        description = '0', 
                        critical_product = True, 
                        key_product = True, 
                        updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        members = [
                            56
                            ], 
                        authorization_groups = [
                            56
                            ], )
                    }, 
                role = {
                    'key' : openapi_client.models.role.Role(
                        id = 56, 
                        name = '0', 
                        is_owner = True, )
                    }, 
                user = {
                    'key' : openapi_client.models.user_stub.UserStub(
                        id = 56, 
                        username = 'a', 
                        first_name = '0', 
                        last_name = '0', )
                    }
            )
        else :
            return InlineResponse20034Prefetch(
        )

    def testInlineResponse20034Prefetch(self):
        """Test InlineResponse20034Prefetch"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
