# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.engagement_presets import EngagementPresets  # noqa: E501
from openapi_client.rest import ApiException

class TestEngagementPresets(unittest.TestCase):
    """EngagementPresets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EngagementPresets
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.engagement_presets.EngagementPresets()  # noqa: E501
        if include_optional :
            return EngagementPresets(
                id = 56, 
                title = '0', 
                notes = '0', 
                scope = '0', 
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                product = 56, 
                test_type = [
                    56
                    ], 
                network_locations = [
                    56
                    ]
            )
        else :
            return EngagementPresets(
                product = 56,
        )

    def testEngagementPresets(self):
        """Test EngagementPresets"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
