# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.endpoint_meta_import_api import EndpointMetaImportApi  # noqa: E501
from openapi_client.rest import ApiException


class TestEndpointMetaImportApi(unittest.TestCase):
    """EndpointMetaImportApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.endpoint_meta_import_api.EndpointMetaImportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_endpoint_meta_import_create(self):
        """Test case for endpoint_meta_import_create

        Imports a CSV file into a product to propogate arbitrary meta and tags on endpoints.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
