# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.dojo_groups_api import DojoGroupsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDojoGroupsApi(unittest.TestCase):
    """DojoGroupsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.dojo_groups_api.DojoGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dojo_groups_create(self):
        """Test case for dojo_groups_create

        """
        pass

    def test_dojo_groups_delete(self):
        """Test case for dojo_groups_delete

        """
        pass

    def test_dojo_groups_list(self):
        """Test case for dojo_groups_list

        """
        pass

    def test_dojo_groups_partial_update(self):
        """Test case for dojo_groups_partial_update

        """
        pass

    def test_dojo_groups_read(self):
        """Test case for dojo_groups_read

        """
        pass

    def test_dojo_groups_update(self):
        """Test case for dojo_groups_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
