# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20056 import InlineResponse20056  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20056(unittest.TestCase):
    """InlineResponse20056 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20056
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20056.InlineResponse20056()  # noqa: E501
        if include_optional :
            return InlineResponse20056(
                count = 56, 
                next = '0', 
                previous = '0', 
                results = [
                    openapi_client.models.user.User(
                        id = 56, 
                        username = 'a', 
                        first_name = '0', 
                        last_name = '0', 
                        email = '0', 
                        last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_active = True, 
                        is_superuser = True, 
                        password = '0', )
                    ]
            )
        else :
            return InlineResponse20056(
                count = 56,
                results = [
                    openapi_client.models.user.User(
                        id = 56, 
                        username = 'a', 
                        first_name = '0', 
                        last_name = '0', 
                        email = '0', 
                        last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_active = True, 
                        is_superuser = True, 
                        password = '0', )
                    ],
        )

    def testInlineResponse20056(self):
        """Test InlineResponse20056"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
