# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.jira_project import JIRAProject  # noqa: E501
from openapi_client.rest import ApiException

class TestJIRAProject(unittest.TestCase):
    """JIRAProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JIRAProject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.jira_project.JIRAProject()  # noqa: E501
        if include_optional :
            return JIRAProject(
                id = 56, 
                project_key = '0', 
                issue_template_dir = '0', 
                component = '0', 
                push_all_issues = True, 
                enable_engagement_epic_mapping = True, 
                push_notes = True, 
                product_jira_sla_notification = True, 
                risk_acceptance_expiration_notification = True, 
                jira_instance = 56, 
                product = 56, 
                engagement = 56
            )
        else :
            return JIRAProject(
        )

    def testJIRAProject(self):
        """Test JIRAProject"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
