# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.user_profile_api import UserProfileApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserProfileApi(unittest.TestCase):
    """UserProfileApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_profile_api.UserProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_profile_list(self):
        """Test case for user_profile_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
