# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.network_locations_api import NetworkLocationsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNetworkLocationsApi(unittest.TestCase):
    """NetworkLocationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.network_locations_api.NetworkLocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_network_locations_create(self):
        """Test case for network_locations_create

        """
        pass

    def test_network_locations_delete(self):
        """Test case for network_locations_delete

        """
        pass

    def test_network_locations_list(self):
        """Test case for network_locations_list

        """
        pass

    def test_network_locations_partial_update(self):
        """Test case for network_locations_partial_update

        """
        pass

    def test_network_locations_read(self):
        """Test case for network_locations_read

        """
        pass

    def test_network_locations_update(self):
        """Test case for network_locations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
