# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.note_history import NoteHistory  # noqa: E501
from openapi_client.rest import ApiException

class TestNoteHistory(unittest.TestCase):
    """NoteHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NoteHistory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.note_history.NoteHistory()  # noqa: E501
        if include_optional :
            return NoteHistory(
                id = 56, 
                current_editor = openapi_client.models.user_stub.UserStub(
                    id = 56, 
                    username = 'a', 
                    first_name = '0', 
                    last_name = '0', ), 
                data = '0', 
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                note_type = 56
            )
        else :
            return NoteHistory(
                data = '0',
        )

    def testNoteHistory(self):
        """Test NoteHistory"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
