# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.risk_acceptance import RiskAcceptance  # noqa: E501
from openapi_client.rest import ApiException

class TestRiskAcceptance(unittest.TestCase):
    """RiskAcceptance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RiskAcceptance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.risk_acceptance.RiskAcceptance()  # noqa: E501
        if include_optional :
            return RiskAcceptance(
                id = 56, 
                name = '0', 
                recommendation = 'A', 
                recommendation_details = '0', 
                decision = 'A', 
                decision_details = '0', 
                accepted_by = '0', 
                path = '0', 
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                expiration_date_warned = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                expiration_date_handled = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                reactivate_expired = True, 
                restart_sla_expired = True, 
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                owner = 56, 
                accepted_findings = [
                    56
                    ], 
                notes = [
                    56
                    ]
            )
        else :
            return RiskAcceptance(
                name = '0',
                owner = 56,
                accepted_findings = [
                    56
                    ],
        )

    def testRiskAcceptance(self):
        """Test RiskAcceptance"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
