# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.product_api_scan_configuration import ProductAPIScanConfiguration  # noqa: E501
from openapi_client.rest import ApiException

class TestProductAPIScanConfiguration(unittest.TestCase):
    """ProductAPIScanConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProductAPIScanConfiguration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.product_api_scan_configuration.ProductAPIScanConfiguration()  # noqa: E501
        if include_optional :
            return ProductAPIScanConfiguration(
                id = 56, 
                service_key_1 = '0', 
                service_key_2 = '0', 
                service_key_3 = '0', 
                product = 56, 
                tool_configuration = 56
            )
        else :
            return ProductAPIScanConfiguration(
                product = 56,
                tool_configuration = 56,
        )

    def testProductAPIScanConfiguration(self):
        """Test ProductAPIScanConfiguration"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
