# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.technologies_api import TechnologiesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTechnologiesApi(unittest.TestCase):
    """TechnologiesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.technologies_api.TechnologiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_technologies_create(self):
        """Test case for technologies_create

        """
        pass

    def test_technologies_delete(self):
        """Test case for technologies_delete

        """
        pass

    def test_technologies_list(self):
        """Test case for technologies_list

        """
        pass

    def test_technologies_partial_update(self):
        """Test case for technologies_partial_update

        """
        pass

    def test_technologies_read(self):
        """Test case for technologies_read

        """
        pass

    def test_technologies_update(self):
        """Test case for technologies_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
