# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.user_contact_infos_api import UserContactInfosApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserContactInfosApi(unittest.TestCase):
    """UserContactInfosApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_contact_infos_api.UserContactInfosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_contact_infos_create(self):
        """Test case for user_contact_infos_create

        """
        pass

    def test_user_contact_infos_delete(self):
        """Test case for user_contact_infos_delete

        """
        pass

    def test_user_contact_infos_list(self):
        """Test case for user_contact_infos_list

        """
        pass

    def test_user_contact_infos_partial_update(self):
        """Test case for user_contact_infos_partial_update

        """
        pass

    def test_user_contact_infos_read(self):
        """Test case for user_contact_infos_read

        """
        pass

    def test_user_contact_infos_update(self):
        """Test case for user_contact_infos_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
