# coding: utf-8

"""
    Defect Dojo API

    To use the API you need be authorized.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class FindingRelatedFields(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'test': 'FindingTest',
        'jira': 'JIRAIssue'
    }

    attribute_map = {
        'test': 'test',
        'jira': 'jira'
    }

    def __init__(self, test=None, jira=None, local_vars_configuration=None):  # noqa: E501
        """FindingRelatedFields - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._test = None
        self._jira = None
        self.discriminator = None

        if test is not None:
            self.test = test
        if jira is not None:
            self.jira = jira

    @property
    def test(self):
        """Gets the test of this FindingRelatedFields.  # noqa: E501


        :return: The test of this FindingRelatedFields.  # noqa: E501
        :rtype: FindingTest
        """
        return self._test

    @test.setter
    def test(self, test):
        """Sets the test of this FindingRelatedFields.


        :param test: The test of this FindingRelatedFields.  # noqa: E501
        :type: FindingTest
        """

        self._test = test

    @property
    def jira(self):
        """Gets the jira of this FindingRelatedFields.  # noqa: E501


        :return: The jira of this FindingRelatedFields.  # noqa: E501
        :rtype: JIRAIssue
        """
        return self._jira

    @jira.setter
    def jira(self, jira):
        """Sets the jira of this FindingRelatedFields.


        :param jira: The jira of this FindingRelatedFields.  # noqa: E501
        :type: JIRAIssue
        """

        self._jira = jira

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FindingRelatedFields):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FindingRelatedFields):
            return True

        return self.to_dict() != other.to_dict()
